config/routes.rb
Rails.application.routes.draw do
  get 'lawyer/index'
  devise_for :users
  root "pages#home"
  get 'pages/home'
get "/cases/:id/accepeted", to: "cases#accept"

   root 'cases#index'
   resources :cases
   
  get "cases", to: "cases#index"
  get "cases/:id/edit", to: "cases#edit", as: :cases_edit
  get "cases/:id/profile", to: "cases#profile", as: :cases_profile

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/case.rb
class Case < ApplicationRecord
  belongs_to :user

end

app/models/lawyer.rb
class Lawyer < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :cases, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:role, :name, :bio, :image, :phone, :lawyer, :status])
      devise_parameter_sanitizer.permit(:account_update, keys: [:role])
    end
    
    private

  # Overwriting the sign_out redirect path method
  def after_sign_out_path_for(users)
    new_user_session_path
  end
end

app/controllers/cases_controller.rb
class CasesController < ApplicationController
    def index
        # if current_user.role == "lawyer"
        # else 
        #     redirect_to root_path
        #  end
         @case = Case.all
        
    end

    def show
       
         @case = Case.find(params[:id])
        end

        def profile
       
          @case = Case.find(params[:id])
         end

      def new
        @case = Case.new
        if current_user.role == "client"
        else 
        redirect_to root_path
        end
    end
     
    

      def edit 
        @case = Case.find(params[:id])
        if current_user.role == "client"
        else 
        redirect_to root_path
        end
        end
      
    def create
      

      puts params
       ca = Case.new(case_params)
       ca.user_id = current_user.id
        ca.save
        redirect_to cases_path
        
        end

    def update
        puts params
        @case = Case.find(params[:id])
        @case.update(case_params)
            
        redirect_to cases_path
        
        if current_user.role == "client"
        else 
        redirect_to root_path
        end
      end

      def accept
        @case = Case.find(params[:id])
        @case.update_attribute(:lawyer, current_user.id)
        @case.update_attribute( :status, true)
        redirect_to cases_path
      end

def destroy
    @case = Case.find(params[:id])
    @case.destroy
   
    redirect_to cases_path
  end

    private
  def case_params
    params.require(:case).permit(:subject, :detail, :opposing_lawyer)
  end

end

app/controllers/lawyer_controller.rb
class LawyerController < ApplicationController
  def index
    @lawyers = Lawyer.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cases_helper.rb
module CasesHelper
end

app/helpers/lawyer_helper.rb
module LawyerHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cases/_form.html.erb
<%= form_for @case do |form| %>


    
  <div class="col-lg-4 col-sm-12">
  <div class="field form-group">
    <p class="mform">
      <%= form.label :subject %><br>
      <%= form.text_field :subject, class: "form-control", required: true %>
    </p>
   
    <p class="mform">
      <%= form.label :detail %><br>
      <%= form.text_area :detail, class: "form-control", required: true %>
    </p>

    <p class="mform"> 
      <%= form.label :opposing_lawyer %><br>
      <%= form.text_field :opposing_lawyer, class: "form-control", required: true %>
    </p>
   
    <p class="mform">
      <%= form.submit class: "btn btn-info" %>
      <%= link_to 'Back', cases_path, class: "btn btn-danger" %>
    </p>

    </div>
    </div>
  <% end %>

app/views/cases/edit.html.erb
<div class="container">
<h1>Edit case</h1>
 
  <%= render 'form' %>
 

</div>

app/views/cases/index.html.erb
<div class="container">

<h1>cases list</h1>
 

<table class="table table-striped table-hover" id="cases-table">
  <thead class="thead-dark">
  <tr>
    <th>Created By</th>
    <th>Subject</th>
    <th>Detail</th>
    <th>Oppossing Lawyer</th>
    <th></th>
  </tr>
  </thead>
 
  <% @case.each do |cases| %>
    <tr>
      <td><%= cases.user.name%></td>
      <td><%= cases.subject %></td>
      <td><%= cases.detail %></td>
      <td><%= cases.opposing_lawyer %></td>
      

      <td><%= link_to 'Show', case_path(cases), class: 'btn btn-warning btn-round btn-just-icon btn-sm' %></td>
      
      <% if current_user.id == cases.user_id %>
      <td><%= link_to 'Edit', edit_case_path(cases), class: 'btn btn-success btn-round btn-just-icon btn-sm' %></td>
      <td><%= link_to 'Profile', cases_profile_path(cases), class: 'btn btn-info btn-round btn-just-icon btn-sm' %></td>
      <td><%= link_to 'Destroy', case_path(cases),
              method: :delete,
              data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-round btn-just-icon btn-sm' %></td>
              <% end%>
      
    </tr>
  <% end %>
</table>

</div>

app/views/cases/new.html.erb
<div class="container">
<h2> ADD NEW CASE </h2>

<%= render 'form' %>

</div>

app/views/cases/profile.html.erb
<div class="container">
<div class="fb-profile">


<%= image_tag(@case.user.image, size: "400x200", alt: "User Image", class: "fb-image-profile thumbnail") %>

<p>
  <strong>E-mail:</strong>
  <%= @case.user.email %>
</p>

<p>
  <strong>Name:</strong>
  <%= @case.user.name %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @case.user.bio %>
</p>

<%= link_to 'Back', cases_path, class: "btn btn-danger" %>
</div>
</div>

app/views/cases/show.html.erb
<div class="container">
<div class="content"
<p>
  <strong>Case Subject:</strong>
 <h1 id="sbj"> <%= @case.subject %></h1>
</p>
 
<p>
  <strong>Case Details:</strong>
  <h3> <%= @case.detail %> </h3>
</p>

<p>
  <strong>Opposing Lawyer:</strong>
  <h4> <%= @case.opposing_lawyer %> </h4>
</p>

<% if @case.status == true %>
<p>
Case reserved by <%= User.find(Case.find(@case.id).lawyer).name %>
</p>
<%end%>
</div>

<%= link_to 'Edit', edit_case_path(@case), class: "btn btn-success" %> |
<%= link_to 'Back', cases_path, class: "btn btn-danger" %> |
<% if @case.status == false && current_user.role == "lawyer" %>
<%= link_to 'Accept', "/cases/#{@case.id}/accepeted", class: "btn btn-danger" %>
<% end %>
</div>

app/views/lawyer/index.html.erb
<div class="container">
<h1>All the Lawyers</h1>



<table class="striped bordered" >
  <tr class="lawyers">
    <th >Lawyer Name</th>
    <th >Image</th>
    <th >Experiance</th>
    <th >bio</th>
    <th >E-mail</th>
  </tr>

  <% @lawyers.each do |lawyer| %>
      <tr>
        <td><%= lawyer.name %></td>
        <td><%= image_tag(lawyer.img, size: "150x100", alt: "Lawyer Image") %></td>
        <td><%= lawyer.experiance %></td>
        <td><%= lawyer.bio %></td>
        <td><%= lawyer.mail %></td>
        
        
        
      </tr>
  <% end %>
</table>
</div>

app/views/layouts/_nav.html.erb
<%# Extract only the part of navbar from bootstrap file then put it here in single file %>

<nav class="navbar navbar-default">
      <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          
          <%= link_to 'SUITS', pages_home_path, class: "navbar-brand" %>
        </div>

        <div class="collapse navbar-collapse" id="navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        <li class="navbar-brand navbar-brand-centered" style="background-color: orangered; margin:1px; color:white;">You're a <%= current_user.role%></li>
        <%end%>  
        <li><%= link_to 'Cases', cases_path %></li> 
          <li><%= link_to 'New Cases', new_case_path %></li> 
          <li><%= link_to 'Lawyers', lawyer_index_path %></li>
          
          <li>
          
          
    
    <%= link_to 'Log Out', destroy_user_session_path, :method => :delete , class: "btn btn-default btn-outline btn-circle collapsed"%> 
            
          </li>
        </ul>

      </div>
      </div>
    </nav>



    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Suits</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  

  <%= render 'layouts/nav' %>
    <%= yield %>

    
  <p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
  </body>
</html>

app/views/pages/home.html.erb
<body class="bg">

</body>